### ISSUE TITLE
What the hell is this?

### ISSUE THREAD

**Issue by LegoStormtroopr** [madChopsCoderAu/Autonomous#3]
Seriously...

![image](https://media.giphy.com/media/608Sqityb8npC/giphy.gif)

**Comment by MichaelZaporozhets** [comment]
This is a highly-serious, autonomous zone

**Comment by MichaelZaporozhets** [comment]
get with the program.

**Comment by LegoStormtroopr** [comment]
Phew... explains everything. So its a shit-posting repo for Aussie developers?

Love it.

**Comment by MichaelZaporozhets** [comment]
Don't ask me, i'm just along for the ride. 

@flatmax invited all of us

**Comment by Maikuolan** [comment]
I already procrastinate far too much with my own projects as it is at the moment. Of course, if anyone was interested, contributions there would always be welcome. ;-)

**Comment by flatmax** [comment]
I notice you've been forking with this super oscillator thingy :
https://oscillator.js.org/

![Super oscillator](https://camo.githubusercontent.com/debd9e4d0f8801cc07145c83748cfedb0b7e1eb8/68747470733a2f2f692e696d6775722e636f6d2f517163457641542e676966)

**Comment by Maikuolan** [comment]
That I have. Awesome looking project. I've been meaning to take a closer look at its code for a while now, but hadn't gotten around to doing so yet, due to being busy with other projects. :-(

I still hope to find the time to pull it apart and look at it more closely at some time this quarter if at all possible.

**Comment by flatmax** [comment]
I had a little play with it ... I like its simplicity.
Nice graphics too.

**Comment by Maikuolan** [comment]
Definitely. :-)

All in all, I'm impressed with it.
